### PR TITLE
Add corfu face

### PR DESCRIPTION
**Pull request by rynffoll**
Added faces for Corfu package

## Screenshots

_Before_
image

_After_
image

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] You've added a before/after screenshot illustrating visually your changes.
- [x] You've updated the readme (if adding/changing configuration options)

Thanks!

### CODE REVIEW

**Comment by rynffoll** [comment]
Example:

_Before_
image


_After_
image

**Comment by thomasf** [comment]
I'm not wild about the currently selected match having less of a highlight than the unmatched ones.

This is whatever mode lsp+company mode uses for prompts in my config looks right now and the current selection is only differentiated by bold foreground

 image

**Comment by rynffoll** [comment]
I guess I could try using `:inverse-video`, how about that?

```emacs-lisp
     `(corfu-current ((,class (:inherit corfu-default :weight bold :inverse-video t))))
```

It would look like this
image

**Comment by thomasf** [comment]
Let's try that!

**Pull request merged**
