### PR TITLE
Update smart-mode-line colors

### PR DESCRIPTION
**Pull request by andschwa**
Per the color conventions.

@thomasf is that sort of what you were thinking in #163?

The faces that weren't defined were those that used the default; but if the convention is to define them anyway, I'll add a commit here shortly.

### CODE REVIEW

**Comment by andschwa** [comment]
More questions:

* What color would you recommend for a process other than magenta?
* Should inheritance of built-in be relied on or not? There are faces that could certainly just inherit default/success/warning/error.
* Is the preference to group faces logically or in the same order that they're defined in the package?

**Comment by a3ammar** [comment]
Can you at least revert c4db87e8d2972b8b8111565215e108dbb799e302 until this gets merged? Surely too many colors used in vain is better than no colors at all for the dark theme.

**Comment by andschwa** [comment]
I would agree @a3ammar and did so in my own fork, but sadly here it's not up to me :/

**Comment by andschwa** [comment]
I've gone ahead and rebased onto master so this can merge cleanly. We may still want to tweak more colors.

**Comment by Malabarba** [comment]
Once this is done, if someone would like to make a couple of small-ish screenshots I'd be very happy to add them to sml's frontpage. I'm afraid the current screenshots have become outdated.

**Comment by thomasf** [comment]
@a3ammar

My opinion is that the current look fits better into the general look of this
theme than it does if more colors are added. This is in part because of
"issues" uncommon in other palettes, solarized does not have bright/dark
version of "accent colors" which makes balancing many colors at once not work
as well.. I've spent many many hours figuring out how to get a good overall
balance over the years and it took at least a year or so until I reached the
decision to systematically reduce overall color usage..

Btw, some colors are currently defined for sml:

* Plain foreground text for the bulk of text: Most individual indicators has
  their specific locations there is very little need to highlight the locations
  further. Also, humans are generally adept at relative locations in (in space)
  so if the mode line itself is easy to spot the rest kind of follows naturally.

* The buffer name is using bold base1, emphasized fg color. (The single most
  important information on the mode line)

* sudo is orange (as a warning to be careful)

* modified/read-only/outside-modified are cyan so they are (as a group) clearly
  visible to the user.

* vc-edited is green.. IIRC, someone said this specific indicator was super
  important to be highlighted so I added the color least intrusive on any
  backgroun. The default location of this indicator is also around the center
  of the mode line which is good because it does not disturb the overall
  left/right weight.

**Comment by thomasf** [comment]
And there is another popular solarized theme for emacs as well.. Having two or three actively maintained  emacs solarized themes which also implements exactly the same looks would also be a waste of everyone's time..

**Comment by a3ammar** [comment]
The problem is the dark version defaults to the light version colors. This is what it looks like on my system:
screen shot 2015-04-14 at 11 32 31 am

**Comment by thomasf** [comment]
@a3ammar thats not right., have you done the `(setq sml/theme nil)` before sml is loaded ?

**Comment by thomasf** [comment]
Here;s how it should look currently:

image

image

**Comment by thomasf** [comment]
closing this because this theme has an aggressive anti color pasta ideology :)

**Pull request closed without merging**
