### PR TITLE
Remove turning on rainbow-mode magic comment

### PR DESCRIPTION
**Pull request by conao3**
rainbow-mode is very useful but whether turn on or off
is the decision of the developer.
Pop up execute magic comment every and every time is
very tired.

### CODE REVIEW

**Comment by wyuenho** [comment]
Yeah I agree with this change. It isn't very useful in this package anyway as it highlights all the palette colors as if they are HTML colors. `fontify-face-mode` is much more suitable for reviewing the colors on the face names.

**Comment by thomasf** [comment]
you know you can uninstall rainbow mode if you don't like it? :)  It's kind of useful, I don't need to see the actual solarized colors, just some representation of them to quickly get an idea about where colors are used. But sure, it doesnt need to be in the footer either.

**Comment by conao3** [comment]
Yes. I already used it in global. So,
> But sure, it doesnt need to be in the footer either.

I agree with it.

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
