### PR TITLE
Rename DEV-GUIDE.md -> CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by conao3**
For common agreement, developers notice `CONTRIBUTING` rather than `DEV-GUIDE`.

### CODE REVIEW

**Comment by thomasf** [comment]
nah, I'm fine with the name.  CONTRIBUTING is more often about practicalities of development workflow, not documentation. We also create a contributing document that refers to DEV-GUIDE if it's needed

**Comment by conao3** [comment]
Well, OK.

**Comment by thomasf** [comment]
You just get the risk that people don't read the CONTRIBUTING file instead because they assume it doesn't contain actual documentation. I think it just moves the problem

**Comment by conao3** [comment]
I cannot understand your comments.

**Comment by thomasf** [comment]
What I mean is that a lot of people don't expect the CONTRIBUTING file to contain actual project documentation which isn't written elsewhere so they might not read it and then we have the same kind of problem as people not reading DEV-GUIDE.

**Pull request closed without merging**
