### PR TITLE
Fix typo in child theme examples

### PR DESCRIPTION
**Pull request by PythonNut**

### CODE REVIEW

**Comment by bbatsov** [comment]
:+1: Thanks!

**Comment by thomasf** [comment]
Thanks. btw. child themes are probably broken ( #196 ) but could possibly be updated to work somehow because of color palette generation was recently moved to it's own function ( #198 )

**Comment by PythonNut** [comment]
@thomasf Sadly, I only figured out that child themes were broken after trying them out myself. I was really excited about them too: they look like a very clean way to personalize the face definitions. (Right now, my face definitions are scattered around in various hooks and `with-eval-after-load` blocks and honestly, it doesn't feel very clean)

**Comment by thomasf** [comment]
It's probably fixable, it just stopped working because of changes in one of the 24.x emacs versions.. I just have not had time to do it.. I used to use it all the time to evaluate changes to the theme before pushing to this repository. I'll look into it when I get a chance.

**Pull request merged**
