### PR TITLE
add support for orderless

### PR DESCRIPTION
**Pull request by ssnnoo**
This adds support for the [orderless](https://github.com/oantolin/orderless) completion style.

current

new

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] You've added a before/after screenshot illustrating visually your changes.

Thanks!

### CODE REVIEW

**Comment by thomasf** [comment]
I'm not fully sure about the colors.. In the screenshot the blue kind of pushed out the single green color coming directly afterwards and make it less noticeable.   I am thinking that to avoid color mess only using 2 alternating colors would be enough since orderless cycles them anyways?

In any case I am merging this because regardless if it can be improved it's better than what we had before which is nothing.

**Comment by ssnnoo** [comment]
Thanks for merging it! But good point. I’ll play around bit and see if I can improve it. In practice one hardly ever uses more than three different narrowing groups.

**Comment by thomasf** [comment]
I would maybe begin with magenta since it's generally the most visible color and I at least tend to draw my attention to it the most so it's a good color to starts a series of multiple colors off with. 

I think the most common colors for various kinds of search highlights in the theme are magenta, yellow and blue, it depends a little bit on context. It's a good start that all of them are used here.

**Comment by ssnnoo** [comment]
Ah, I started with yellow because this is currently used for ivy and thought this would give consistency. But much better to start with a brighter colour. I will prepare a pull request later today.

**Pull request merged**
