### PR TITLE
Add autoload for external API functions

### PR DESCRIPTION
**Pull request by conao3**
Hi! I add autoload for external API functions.

### CODE REVIEW

**Comment by bbatsov** [comment]
API functions should not be autoloaded - only user commands are meant to be autoloaded. If you're using an API you're supposed to require its library.

**Comment by conao3** [comment]
So why does `solarized-create-color-palette` have autoload cookies?
The function I added a cookie has a function similar to `solarized-create-color-palette`, but rather calls it.
If there is an autoload cookie, the user can omit an explicit `require`.

**Comment by conao3** [comment]
Sorry I use `external API` as `not internal`. These functions I added autoload cookie documented and the user should use them.

**Comment by bbatsov** [comment]
> So why does solarized-create-color-palette have autoload cookies?

Because someone made a mistake. :-) We just have to remove all autoloads. 

> If there is an autoload cookie, the user can omit an explicit require.

As I said - autoloads are not intended to be used in this manner and we should not abuse them.

**Comment by conao3** [comment]
In my understanding, `autoload` should be added all `entry point` function.
`Entry point` is when not loaded the whole package but activated it.

The user uses `solarized-create-theme-file` then `load-theme` that file.
Currently, the user needed `(require 'solarized)` before them but if there are `autoload` cookies, he can omit explicit `require`.

**Comment by thomasf** [comment]
The emacs manual says:

The most common items to autoload are the **interactive entry** points to a library

**Comment by thomasf** [comment]
I think that just using the `###autoload` thing will always wrap a function inside an loading proxy thats interactive but that maybe has changed since I last fiddled with those things (a few emacs major versions ago).

**Comment by conao3** [comment]
Yes, **common**.
But there are entry-pointable functions if the function is non-interactive. You know `use-package` or `bind-key`, don't you?. They are non-interactive but because they are entry point functions, added `autoload` cookie.

I think to remove `autoload` cookie for `solarized-color-blend` too, but `solarized-create-theme-file` etc should be specified autoloaded.

**Comment by thomasf** [comment]
We won't add more autoload cookies, just require the features if you need them elsewhere. Already present autoloads stays for now to stay backwards compatible.

**Pull request closed without merging**
