### PR TITLE
Enable lexical-binding and some code-refactoring

### PR DESCRIPTION
**Pull request by conao3**
Hi!
This PR related #352.  This PR enables lexical-binding, change
child-theme format but I cannot figure out
`custom--inhibit-theme-enable` hack.

So I remain `custom--inhibit-theme-enable` to nil to works well
child-theme feature.

### CODE REVIEW

**Comment by thomasf** [comment]
I will check this maybe tomorrow evening, have to do other things for a day or maybe two.

**Comment by conao3** [comment]
OK!

**Comment by thomasf** [comment]
I think we should be more careful about doing things that potentially breaks someone usage.  Maybe we could even move the work to a separate branch not picked up by MELPA for a little while to get a new stable 2.0 version done, what I don't want is to potentially break things too often by not having a clear end goal.  I am not going to merge this because currently it doesn't really fully solve a problem someone actually has (?)

For the short term I will mostly be working on getting rid of all uses of  the accent color -l -d -hc -lc variants usage inside the theme OR clearly define what those colors are and how they should be used. I will try to compile my list of the the best and worst things about how the theme works and what I might expect if it were to have a changed API

**Comment by conao3** [comment]
First, it is wrong to use macros in functions that contain things that you want to change dynamically.
To that end, we're using an dirty `eval`, and in previous versions, it was forced disabling compilation.
Here is some advice from Emacs maintainers.
```elisp
(defmacro dont-compile (&rest body)
  "Like `progn', but the body always runs interpreted (not compiled).
If you think you need this, you're probably making a mistake somewhere."
  (declare (debug t) (indent 0) (obsolete nil "24.4"))
  (list 'eval (list 'quote (if (cdr body) (cons 'progn body) (car body)))))
```
And `lexical-binding nil` is not in line with MELPA's criteria.
Here is the asymmetry of MELPA, MELPA will not be given the opportunity to review once registered packages.
Now it will be difficult to pass the MELPA maintainer review.

My change allows byte-compilation of the entire solarize, no function wrapping macros, and `lexical-binding` can be enabled.
It’s true that I’ve rewritten many things, so it’s only natural to spend time on reviews. However, keeping this branch and repeating other changes is not a good choice.
At some stage, I will be reluctant to resolve conflicts, and this branch will not be maintained and it will never be merged.

**Comment by bbatsov** [comment]
For the protocol - I like the proposed changes. I do feel, however, that all this theme creation machinery has to be documented somewhere as now it's pretty weird. The README doesn't even mention the extra themes shipped with Solarized lately.

**Comment by thomasf** [comment]
Why don't you use the `solarized-` prefix for `with-solarized-color-variables`?

**Comment by conao3** [comment]
Because of Elisp and Lisp conventions.
`solarized-with-color-variables` defines a macro that binds the color palette to the appropriate let variable and executes the `body` in that `let` environment.

A macro that accepts such a body and temporarily executes an S-expression in a different environment has a `with-` prefix to give Lisp programmers a proper understanding.
I believe that we should follow `package-lint` entirely, and using the `with-` prefix is legal under the direction of package-lint.
see https://github.com/purcell/package-lint/pull/146

**Comment by alphapapa** [comment]
@conao3 Steve said on that issue that he does *not* encourage doing this:

> This is fine, but I'm generally a little -1 on allowing these various prefixes, because there are usually reasonable possible alternatives, and these prefixes aren't often used anyway: I wouldn't want to actively encourage them.

What benefit is there to changing the macro's name from `solarized-with-color-variables` to `with-solarized-color-variables`?  It's already correct according to MELPA and Elisp guidelines: it begins with the package prefix (which is the most important, because it aids discovery of a package's functions and macros in Emacs help facilities), then the `with` prefix, then the rest of the name.  The docstring is to explain what it actually does.

> Here is the asymmetry of MELPA, MELPA will not be given the opportunity to review once registered packages.  Now it will be difficult to pass the MELPA maintainer review.

MELPA has thousands of packages that were added before its requirements were more strictly enforced.  It is not necessary, nor even necessarily helpful, to make such changes for the sake of making such changes.

Please do not make these kinds of churning changes that do not benefit users.

> At some stage, I will be reluctant to resolve conflicts, and this branch will not be maintained and it will never be merged.

This sounds like you're trying to leverage code you wrote which has changes that are desired to force through changes that are not desired.  "Merge all of the changes or I will let them rot" is not a good attitude.

**Comment by conao3** [comment]
What is the **user benefit** that you claim?
If you only want to use the code at a certain point forever, you can specify a commit hash in Cask and continue to use it personally. It is your choice and do as you please.

There're no meanings more than shortening the life of the Emacs community by stopping people from writing better code by interfering with them.

It is important to follow the package-lint warning.
This simply indicates the maintenance status of the package, and a package that has been left with dozens of warnings gives a dangerous signal about the maintenance status.

**Comment by alphapapa** [comment]
You've said several times now, in this and other issues, that I should not criticize proposals, because if I do, people will stop working on the project, and it will die.  Therefore, it is implied, all proposals are a net positive, and your proposals must be accepted as-is.  

It's impossible to reason about technical issues by starting from that premise.  It is a very hostile attitude to insist that your proposals be accepted or you will stop working on the project.

**Comment by conao3** [comment]
When did I insist that it should be accepted as-is?
As a user of this package, I just make suggestions to improve the package.
And it is rare for a proposal to be accepted as it is, and in many cases, with the maintainer advice try to modify the proposal and cooperate with it.

You just block it. There is only one point. Don't change the code.
This only prevents the package from continuing to evolve, and it will be also detrimental to you if this package is not updated.

**Comment by alphapapa** [comment]
We don't seem to be communicating very well about these issues.  I don't know why.  But I won't bother you about them anymore.  I look forward to the planned improvements.

**Comment by thomasf** [comment]
I'm not a big fan of with- . Doing a quick apropos for after force loading my 500+ packages elpa revelaes that it's probably not a widely used idiom. packatename-with-... is much more common and what I personally would expect from anything not in the standard library. Just because a linter rule checker alllows for something does no always imply that it's the right thing to do.
When i personally don't remember exactly what some package function  I always start by doing `C-h f` `packagename-` `COMPLETE`  to quickly see a list.  I just expect packages to stay in their prefixes because it's a sane overall method of organizing things.

**Comment by conao3** [comment]
OK. Fix that.

**Comment by thomasf** [comment]
I am holding off doing any more commits to master btw until this is either merged or decided against.  It certainly looks like a good step on the path towards a better package.

I so much would like the child theme functionality just be removed and reintroduced later in a better way that actually works but it still possible to use it now even in its broken stage and don't want remove it without having an alternative.

Even if it's not overwriting already set faces correctly it still works for my custom-set-variables:

```el
(defun my-solarized-theme ()
  "My solarized child theme."

  (custom-theme-set-faces
   theme-name


   ;;                                  _
   ;;  _ __  ___ _ _ ___ ___ _ _  __ _| |
   ;; | '_ \/ -_) '_(_-</ _ \ ' \/ _` | |
   ;; | .__/\___|_| /__/\___/_||_\__,_|_|
   ;; |_|
   ;; what other people might not want


   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,base02))))

   )

  (custom-theme-set-variables
   theme-name

   `(org-todo-keyword-faces
     (quote (("TODO" :foreground ,cyan :weight bold :slant italic :underline nil)
             ("NEXT" :foreground ,blue :weight bold :slant italic :underline nil)
             ("ACTIVE" :foreground ,blue :weight bold :slant italic :underline nil)
             ("DONE" :foreground ,base01 :weight bold :slant italic :underline nil)
             ("WAITING" :foreground ,yellow :weight bold :slant italic :underline nil)
             ("HOLD" :foreground ,yellow :weight bold :slant italic :underline nil)
             ("NOTE" :foreground ,green :weight bold :slant italic :underline nil)
             ("SOMEDAY" :foreground ,base01 :weight bold :slant italic :underline nil)
             ("CANCELLED" :foreground ,base01 :weight bold :slant italic :underline nil)
             ("PHONE" :foreground ,blue :weight bold :slant italicg :underline nil))))

   `(jump-char-lazy-highlight-face nil)
   `(org-tag-faces
     '(("@home"  :foreground ,green)
       ("@office" :foreground ,blue)
       ("@errand" :foreground ,cyan)
       ("@travel" :foreground ,violet)
       ("task"  :foreground ,yellow)
       ("bug"  :foreground ,yellow)
       ("enhancement"  :foreground ,yellow)
       ("work" :slant italic :foreground ,base01)
       ("personal" :slant italic :foreground ,base01)
       ("23c" :slant italic :background ,base02)
       ("bulk" :foreground ,base01)
       ("hold" :foreground ,green)
       ("note" :foreground ,base01)
       ("waiting" :foreground ,orange)
       ("cancelled" :foreground ,green  )
       ("flagged" :foreground ,red))

     ;; custom-set-variables end
     )))
```

**Comment by conao3** [comment]
I have not removed the child-theme functionality. The explanation is included in another PR(#355 ).
In fact, it's important to create a theme file and how to run the theme.
I changed both to make lexical-binding work, but with a simple change you can use child-theme under a new mechanism.

In your example, you can simply delete the function name, arguments, and docstring and pass it as a list to the theme creation function.
In these situations, you should use Lisp's **homoiconic** rather than functions, and this method works well with lexical-binding.

**Comment by thomasf** [comment]
Or may

> The README doesn't even mention the extra themes shipped with Solarized lately.

Yeah, my bad. I will add that to the readme after this and the other readme change has been merged. Need some time to think about how to formulate that text in an approachable way anyways.

**Comment by thomasf** [comment]
> I have not removed the child-theme functionality. The explanation is included in another PR(#355 ).
I'm not saying you have. It's probably best to repair it towards something that is more like it worked (I guess before emacs theme system changed something internally) now and postpone any potential structural changes to customization to a later date.

> In fact, it's important to create a theme file and how to run the theme.
Yeah, I just remembered that function, I have just tried it briefly and not actually used it yet. 

We are still relying on `custom--inhibit-theme-enable` which from what I can tell will in general sitirr up how the emacs theme system applies themes over eachother?

Did you have any thought about the solution of just running it before the themes own custom-set-faces instead? I don't know if custom-set-variables has the same "write protection" rules though, if thats not the case we are just exchanging one problem for another by changing the order.

**Comment by conao3** [comment]
I found child-theme does not work well. Please, some time to investigate.

**Comment by conao3** [comment]
Issue solved.
And I think `custom--inhibit-theme-enable` related issue should be improved another PR or commits.

**Comment by thomasf** [comment]
I will try actually using this branch later in the week end to see if I find any problems

**Comment by conao3** [comment]
OK. Please test.

**Comment by thomasf** [comment]
please don't remove the child themes from the repository, I need those to be available when using the `make dev` environment to be sure that they are always working as expected. I think it's even a good idea to set an very hard color in them like making the foreground color #ff0000 or something so it's always clear that they actually do work.

**Comment by conao3** [comment]
Revert remove child-theme example files commit. and fix those files to fit new API.

**Comment by thomasf** [comment]
solarized-wombat-dark-theme.el does not work since it now creates a theme file instead of actually being a theme (?).

I think you can move it to the minimal-init test env for now, I can take care of loading it into the test env after merge.

I'm thinking that we maybe should add a changelog/migration file that just explains what people should do if they have an old child theme and what to use it now. Just something that people that don't know elisp can follow.

**Comment by conao3** [comment]
Thanks for your point. I fix that.
BTW, I have thought these `sample` theme files should remove. But the discussion is another issue.

**Comment by thomasf** [comment]
Yeah, the extra theme files can be moved into their own elpa package also build from this repository or something. I still want them to be installable but since they cause confusion about what they are it's probably for the best to not have them in the main package.

I'm probably merging this within a hour or so now.  Maybe add an upgrade.guide.md in the root aftewards. I'm thinking along the lines of a format something like this (just placeholder content atm)

# solarized theme upgrade guide


## 2019-11-17

If you are using child themes you need to modify your child themes like this

### before

**my-solarized.el**

```el
(require 'solarized)

(defun my-solarized-theme ()
  "My solarized child theme."
  (custom-theme-set-faces
   theme-name
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,base02)))))
  (custom-theme-set-variables
   theme-name
   `(org-todo-keyword-faces
     (quote (("TODO" :foreground ,cyan :weight bold :slant italic :underline nil))))))

(provide 'my-solarized)
```

**my-solarized-dark-theme.el**
```el
(require 'solarized)
(require 'my-solarized)

(deftheme my-solarized-dark "The light variant of the Solarized colour theme")
(create-solarized-theme 'dark 'my-solarized-dark 'my-solarized-theme)

(provide-theme 'my-solarized-dark)
```


### after

**my-solarized.el**
```
(require 'solarized)

(setq my-solarized-childtheme  '(
    (custom-theme-set-faces
       theme-name
       `(rainbow-delimiters-depth-1-face ((,class (:foreground ,base02)))))
      (custom-theme-set-variables
       theme-name
       `(org-todo-keyword-faces
         (quote (("TODO" :foreground ,cyan :weight bold :slant italic :underline nil))))))
    )
)
(provide 'my-solarized)
```

**my-solarized-dark-theme.el**

```el
...
```

**Comment by conao3** [comment]
LGTM.

**Comment by thomasf** [comment]
I would prefer a single commit to merge.. 

I think this might be one of the paths of least resistance to create a rebased merge out of these changes: 

I can do it myself but then you won't be the author in git.

```sh
git merge -Xignore-space-change master
git reset master
git add -A
git commit -m"...."
```

**Comment by conao3** [comment]
rebased.

**Comment by conao3** [comment]
Thanks!

**Comment by thomasf** [comment]
the readme update references wrong function names

**Pull request merged**
