### PR TITLE
Explicitly extend many faces beyond eol for Emacs 27 (version 2)

### PR DESCRIPTION
**Pull request by tarsius**
This replaces #359.

This doesn't fix all affected faces, but it at least makes new solarized usable with new emacs, at least for me.

### CODE REVIEW

**Comment by thomasf** [comment]
By emacs 27 do you mean the current master branch of the Emacs repository?

**Comment by tarsius** [comment]
Yes.

**Comment by thomasf** [comment]
Just for reference if anyone is wondering.. 

enacs 27 without this patch 

image


emacs 26

image

**Comment by thomasf** [comment]
emacs 26 keeps working as before so I see no harm in merging this for people who runs pre release version of emacs.

**Comment by tarsius** [comment]
Since https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=58fb4c3e68a4a42ad491d0fa2c084e5c39942e2b this isn't necessary anymore and should be reverted.

**Pull request merged**
